version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile-dev
    expose:
      - 3001
    env_file: ./config/.env
    ports:
      - 3001:3001
    volumes:
      - ./server/:/app/server/
    command: npm run start
    restart: always

  client:
    build:
      context: ./client
      dockerfile: Dockerfile-dev
    environment:
      - REACT_APP_PORT=3000
      - CHOKIDAR_USEPOLLING=true
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    links:
      - server
    command: npm run start
    restart: always
